### ISSUE TITLE
Async EOD client for historical data

### ISSUE THREAD

**Issue by ttamg** [LautaroParada/eod-data#32]
Hi there.  Nice simple implementation of the EOD API.  I'm using it for historical data currently.

Any thoughts or plans for doing an async version of the Python client?  
The question if so is whether to set up a separate async class you can import (probably the cleanest) or try to integrate into one class and detect if it is working in async or blocking mode (probably the cleverest).
If you are thinking of bringing this into scope, I'm happy to contribute.

@LautaroParada - are you associated with the company EOD?  I'm wondering if this could become the official supported version of the Python API.

**Comment by LautaroParada** [comment]
Hi @ttamg, thank you! Currently, I'm working on the async version, and I'm trying to implement it with the `EodHistoricalData` instance to have every single functionality under the same "umbrella." Hopefully, it will be released in conjunction with the new APIs ([Tweets Sentiment API](https://eodhistoricaldata.com/financial-apis-blog/tweets-sentiment-api/) and [Cryptocurrency Fundamental Data API](https://eodhistoricaldata.com/financial-apis-blog/cryptocurrency-fundamental-data-api/)) during July (version 0.2.1). If you have any idea about implementing the async functionality, it's more than welcome!

No, I'm not affiliated in any way with the company EOD. I'm a trader who likes to automate my research and trading strategies. I've contacted the team, and the client is in their [documentation](https://eodhistoricaldata.com/financial-apis/python-financial-apis-sdk/), so I'm more than happy with that.

**Comment by ttamg** [comment]
Sure thing.  Sounds good.  

On my ideas if it is helpful:
1) the one approach is to have a separate async client with the same named methods, but one uses async coroutines and the other has sync methods.   Miguel Grindberg does it that way on the `python-socketio` package - see here https://github.com/miguelgrinberg/python-socketio/tree/main/src/socketio.  One of the Binance APIs does it this way too - https://github.com/sammchardy/python-binance/blob/master/binance/client.py
2) Another is to have duplicated methods under the same `EodHistoricalData` object with the async methods prepended with `async_...` or similar.
3) Another theoretically would be to define sync or async in the constructor of `EodHistoricalData` and that then attaches the sync or async methods as part of that `__init__()`.  But to me that is less useful as there may be cases where you want to mix async and sync methods.

I think 3 is over-engineered but 1 or 2 works.  My personal preference is for 1 as to then move to async all you need to do is change the client.  

Hope this helps.

**Comment by LautaroParada** [comment]
Thank you very much @ttamg! These are great options. I will check what works best, and hopefully, during Q3 it will be implemented. In the meantime, for July, I will update the [Tweets Sentiment API](https://eodhistoricaldata.com/financial-apis-blog/tweets-sentiment-api/) and [Cryptocurrency Fundamental Data API](https://eodhistoricaldata.com/financial-apis-blog/cryptocurrency-fundamental-data-api/).

**Comment by ttamg** [comment]
Hi @LautaroParada - how are you getting on with thinking about the async option?  Let me know if you need some further support.  In the meantime threading async support can be provided by people if they use the `unsync` library decorator I think.
